# (ohmy)zsh options
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="bira"
plugins=(git zsh-syntax-highlighting tmux)
source $ZSH/oh-my-zsh.sh
CASE_SENSITIVE="true"
DISABLE_AUTO_TITLE="true"
setopt NO_NOMATCH
setopt PROMPT_SUBST
setopt extendedglob
setopt nonomatch

# aliases
alias :q='exit'
export TERM=screen-256color

if [[ -f /usr/bin/virtualenvwrapper.sh ]] ; then
  # virtualenv(wrapper)
  export WORKON_HOME=$HOME/virtualenvs
  export PIP_VIRTUALENV_BASE=$WORKON_HOME
  export PIP_RESPECT_VIRTUALENV=true
  VIRTUAL_ENV_DISABLE_PROMPT=1
  source /usr/bin/virtualenvwrapper.sh
fi

export EDITOR=vim
