---

- include: ../../vm-host/tasks/build-vm.yml
  vars:
    name: sonarr
    memory_mb: 1024
    cpus: 1
    disk_size: 20G
    disk_image: sonarr-guest.img
    metadata_image: sonarr-config.iso
    mac_address: de:ad:be:ef:db:57
