---
- name: Set hostname
  hostname: name=nginx.jroll.io
  become: yes
  become_method: sudo

- name: Install nginx
  apt: name=nginx update_cache=yes
  become: yes
  become_method: sudo

- name: Run nginx
  service: name=nginx state=started enabled=yes
  become: yes
  become_method: sudo
