---
- name: ensure UTC
  shell: timedatectl set-timezone UTC

- name: upgrade all packages
  dnf: name=* state=latest
  become: yes
  become_method: sudo

- name: install basic packages
  dnf: name={{ item }} state=latest
  become: yes
  become_method: sudo
  with_items:
    - libselinux-python
    - vim-enhanced
    - the_silver_searcher

- include: zsh.yml
- include: tmux.yml
- include: git.yml
